export const GET_ALL_ITEMS_REQUEST = 'GET_ALL_ITEMS_REQUEST';
export const GET_ALL_ITEMS_SUCCESS = 'GET_ALL_ITEMS_SUCCESSS';
export const GET_ALL_ITEMS_FAIL = 'GET_ALL_ITEMS_FAIL';

export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';

export const UPDATE_PURCHASE_STATE_REQUEST = 'UPDATE_PURCHASE_STATE_REQUEST';
export const UPDATE_PURCHASE_STATE_SUCCESS = 'UPDATE_PURCHASE_STATE_SUCCESS';
export const UPDATE_PURCHASE_STATE_FAIL = 'UPDATE_PURCHASE_STATE_FAIL';
export const UPDATE_PURCHASE_STATE_RESET = 'UPDATE_PURCHASE_STATE_RESET';

export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAIL = 'DELETE_ITEM_FAIL';
export const DELETE_ITEM_RESET = 'DELETE_ITEM_RESET';
